name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_mode: ["Debug", "Release"]
      fail-fast: false
    name: GCC - ${{ matrix.build_mode }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true

      - name: Update apt
        run: sudo apt update -y

      - name: Install JUCE dependencies
        run: >
          sudo apt install -y
          ninja-build
          ccache
          libasound2-dev
          libjack-jackd2-dev
          ladspa-sdk
          libcurl4-openssl-dev
          libfreetype6-dev
          libx11-dev
          libxcomposite-dev
          libxcursor-dev
          libxcursor-dev
          libxext-dev
          libxinerama-dev
          libxrandr-dev
          libxrender-dev
          libwebkit2gtk-4.0-dev
          libglu1-mesa-dev
          mesa-common-dev

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: jml-linux-build-${{ matrix.build_mode }}

      - name: Install conan
        run: |
          pip install -r requirements.txt
          conan profile detect --force

      - name: CMake configure
        run: >
          cmake
          -S .
          -G Ninja
          -B build
          -D CMAKE_BUILD_TYPE=${{ matrix.build_mode }}
          -D CMAKE_PROJECT_TOP_LEVEL_INCLUDES=external/cmake-conan/conan_provider.cmake

      - name: CMake build
        run: cmake --build build --parallel 1

      - name: CTest
        run: ctest --test-dir build -C ${{ matrix.build_mode }} --output-on-failure
