name: macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-12
    strategy:
      matrix:
        build_mode: ["Debug", "Release"]
      fail-fast: false
    name: AppleClang - ${{ matrix.build_mode }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true

      - name: Install dependencies
        run: |
          brew install ninja ccache
          pip3 install -r requirements.txt
          conan profile detect --force

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: jml-macos-build-${{ matrix.build_mode }}

      - name: CMake configure
        run: >
          cmake
          -S .
          -G Ninja
          -B build
          -D CMAKE_BUILD_TYPE=${{ matrix.build_mode }}
          -D CMAKE_PROJECT_TOP_LEVEL_INCLUDES=external/cmake-conan/conan_provider.cmake

      - name: CMake build
        run: cmake --build build

      - name: CTest
        run: ctest --test-dir build -C ${{ matrix.build_mode }} --output-on-failure
