name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        build_mode: ["Debug", "Release"]
      fail-fast: false
    name: MSVC - ${{ matrix.build_mode }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          conan config set general.revisions_enabled=1

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: CMake configure
        run: >
          cmake
          -S .
          -G "Ninja"
          -B build
          -D CMAKE_BUILD_TYPE=${{ matrix.build_mode }}

      - name: CMake build
        run: cmake --build build

      - name: CTest
        run: ctest --test-dir build -C ${{ matrix.build_mode }} --output-on-failure
